PetAdoptionMVC/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PetAdoption.DataAccess.Repository.IRepository;
using PetAdoption.Models;
using PetAdoption.Utility;

namespace PetAdoptionMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;

            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            List<Product> objProductList = _unitOfWork.product.GetAll().ToList();

            return View(objProductList);
        }

        public IActionResult Upsert(int? id)
        {
            if (id == null || id == 0)
            {
                return View();
            }
            else
            {
                Product objProduct = _unitOfWork.product.Get(u => u.Id == id);

                return View(objProduct);
            }
        }

        [HttpPost]
        public IActionResult Upsert(Product product, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;

                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);

                    string productPath = Path.Combine(wwwRootPath, @"Images\Products");

                    if (!string.IsNullOrEmpty(product.PhotoUrl)) 
                    {
                        var oldPhotoPath = Path.Combine(wwwRootPath, product.PhotoUrl.TrimStart('/'));

                        if (System.IO.File.Exists(oldPhotoPath)) 
                        {
                            System.IO.File.Delete(oldPhotoPath);
                        }
                    }

                    using (var fileStream = new FileStream(
                        Path.Combine(productPath, fileName),
                        FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }

                    product.PhotoUrl = @"/Images/Products/" + fileName;

                }

                if (product.Id == 0)
                {
                    _unitOfWork.product.Add(product);

                    _unitOfWork.Save();

                    TempData["success"] = "Product added successfully";
                }
                else

                {
                    _unitOfWork.product.Update(product);

                    _unitOfWork.Save();

                    TempData["success"] = "Product updated successfully";
                }

                return RedirectToAction("Index");
            }

            var errors = ModelState.Values.SelectMany(x => x.Errors);

            foreach (var error in errors)
            {
                TempData["error"] = error.ErrorMessage;

                break;
            }

            return View();
        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll() 
        {
            List<Product> objProductList = _unitOfWork.product.GetAll().ToList();
            return Json(new {  data = objProductList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id) 
        {
            Product? productToBeDeleted = _unitOfWork.product.Get(u =>u.Id == id);
            Listing? listingFromDb = _unitOfWork.listing.Get(u => u.ProductId == id);

            if (productToBeDeleted is null) 
            {
                return Json(new { success = false, message = "Error while deleting" }); 
            }

            if (productToBeDeleted.PhotoUrl is not null) 
            {
                var oldPhotoPath = Path.Combine(_webHostEnvironment.WebRootPath, productToBeDeleted.PhotoUrl.TrimStart('/'));
                
                if (System.IO.File.Exists(oldPhotoPath))
                {
                    System.IO.File.Delete(oldPhotoPath);
                }
            }

            _unitOfWork.product.Remove(productToBeDeleted);

            if(listingFromDb is not null) 
            {
                _unitOfWork.listing.Remove(listingFromDb);
            };

            _unitOfWork.Save();

            return Json(new { success = true, message = "Product removed successfully" });
        }

        #endregion

    }
}

PetAdoptionMVC/Areas/Customer/Controllers/ListingController.cs
using Microsoft.AspNetCore.Mvc;
using PetAdoption.Models;
using PetAdoption.DataAccess.Data;
using PetAdoption.DataAccess.Repository.IRepository;
using PetAdoption.DataAccess.Repository;

namespace PetAdoptionMVC.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class ListingController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        
        public ListingController(IUnitOfWork unitOfWork) 
        {
            _unitOfWork = unitOfWork;
        }
        
        public IActionResult ProductListings()
        {
            List<int?> existingProductIds = _unitOfWork.listing.GetAll().Select(l => l.ProductId).ToList();

            List<Product> allProducts = _unitOfWork.product.GetAll().ToList();

            List<Product> missingProducts = allProducts.Where(p => !existingProductIds.Contains(p.Id)).ToList();

            foreach (Product product in missingProducts)
            {
                Listing newListing = new Listing
                {
                    ProductId = product.Id,
                    Price = 14.85m
                };

                _unitOfWork.listing.Add(newListing);
            }

            _unitOfWork.Save();

            List<Listing> objProductListings = 
                _unitOfWork.listing.GetAll(includeProperties: "Product")
                .Where(listing => listing.Product is not null).ToList();

            return View(objProductListings);
        }

        public IActionResult AnimalListings() 
        {
            List<int?> existingAnimalIds = _unitOfWork.listing.GetAll().Select(l => l.AnimalId).ToList();

            List<Animal> allAnimals = _unitOfWork.animal.GetAll().ToList();

            List<Animal> missingAnimals = allAnimals.Where(a => !existingAnimalIds.Contains(a.Id)).ToList();

            foreach (Animal animal in missingAnimals) 
            {
                Listing newListing = new Listing
                {
                    AnimalId = animal.Id,
                    Price = 100.00m
                };


                _unitOfWork.listing.Add(newListing);
            }

            _unitOfWork.Save();

            List<Listing> objAnimalListings = 
                _unitOfWork.listing.GetAll(includeProperties: "Animal")
                .Where(listing => listing.Animal is not null).ToList();

            return View(objAnimalListings);
        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAllProductListings()
        {
            List<Listing> objProductListings =
                _unitOfWork.listing.GetAll(includeProperties: "Product")
                .Where(listing => listing.Product is not null).ToList();

            return Json(new { data = objProductListings });
        }
        
        [HttpGet]
        public IActionResult GetAllAnimalListings()
        {
            List<Listing> objAnimalListings =
                _unitOfWork.listing.GetAll(includeProperties: "Animal")
                .Where(listing => listing.Animal is not null).ToList();

            return Json(new { data = objAnimalListings });
        }

        #endregion
    }
}

PetAdoptionMVC/Controllers/AnimalController.cs
using Microsoft.AspNetCore.Mvc;
using PetAdoption.Models;
using PetAdoption.DataAccess.Data;
using PetAdoption.DataAccess.Repository.IRepository;

namespace PetAdoptionMVC.Controllers
{
    public class AnimalController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public AnimalController(IUnitOfWork unitOfWork) 
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<Animal> objAnimalList = _unitOfWork.animal.GetAll().ToList();
            return View(objAnimalList);
        }
        public IActionResult Create() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Animal animal) 
        {
            if(ModelState.IsValid) 
            {
                _unitOfWork.animal.Add(animal);
                _unitOfWork.Save();
                TempData["success"] = "Animal added successfully";

                return RedirectToAction("Index");
            }
            TempData["error"] = "Error adding animal";
            return View();
   
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0) 
            {
                return NotFound();
            }
            Animal? animalFromDb = _unitOfWork.animal.Get(u=>u.Id==id);

            if (animalFromDb == null) 
            {
                return NotFound();
            }

            return View(animalFromDb);
        }

        [HttpPost]
        public IActionResult Edit(Animal animal) 
        {
            if (ModelState.IsValid) 
            {
                _unitOfWork.animal.Update(animal);
                _unitOfWork.Save();
                TempData["success"] = "Animal updated successfully";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Error adding animal";
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0) 
            {
                return NotFound();
            }

            Animal? animalFromDb = _unitOfWork.animal.Get(u => u.Id == id);

            if (animalFromDb == null) 
            {
                return NotFound();
            }

            return View(animalFromDb);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult Delete(int id) 
        {
            Animal? animalFromDb = _unitOfWork.animal.Get(u => u.Id == id);

            if(animalFromDb == null) 
            {
                return NotFound();
            }

            _unitOfWork.animal.Remove(animalFromDb);
            _unitOfWork.Save();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");
        }

    }
}

PetAdoptionMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetAdoptionMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/PetAdoptionMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.0.1/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
</head>
<body>
    <header class="stick-me-top">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow crisp-text">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">PetAdoptionMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item nav-link-border-underline mr-1">
                            <a class="nav-link text-light" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>                                
                        <li class="nav-item nav-link-border-underline mr-1">
                            <a class="nav-link text-light " asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item nav-link-border-underline mr-1">
                            <a class="nav-link text-light " asp-area="Customer" asp-controller="Listing" asp-action="AnimalListings">Animals</a>
                        </li>
                        <li class="nav-item nav-link-border-underline mr-1">
                            <a class="nav-link text-light " asp-area="Customer" asp-controller="Listing" asp-action="ProductListings">Products</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item nav-link-border-underline ml-1">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="true">Admin</a>
                                <div class="dropdown-menu" data-bs-popper="static">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Animal" asp-action="Index">Animals</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Products</a>
                                </div>
                            </li>                            
                        }
                        
                    </ul>
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-light bg-primary">
        <div class="container">
            PetAdoptionMVC <svg width="3rem" height="3rem" viewBox="0 0 128 128" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--noto" preserveAspectRatio="xMidYMid meet" transform="scale(-1,1)"><ellipse transform="rotate(-6.212 96.651 75.058)" cx="96.65" cy="75.06" rx="7.46" ry="10.19" fill="#f8f9fa"></ellipse><ellipse transform="rotate(-3.438 45.482 24.473)" cx="45.49" cy="24.46" rx="7.7" ry="10.06" fill="#f8f9fa"></ellipse><ellipse transform="rotate(-83.131 62.972 30.562)" cx="62.97" cy="30.56" rx="9.6" ry="7.7" fill="#f8f9fa"></ellipse><ellipse transform="rotate(-13.239 27.21 27.8)" cx="27.21" cy="27.8" rx="7.83" ry="10.74" fill="#f8f9fa"></ellipse><path d="M89.66 94.36c15.11-8.45 32.4 3.47 30.13 12.58c-2.44 9.76-11.73 4.5-18.68 7.04c-4.27 1.56-10.79 10.32-18.3 4.97c-6.55-4.67-3.01-19.08 6.85-24.59z" fill="#f8f9fa"></path><path d="M38.16 40.41c10.8-2.83 25.86 5.56 24.14 15.13c-1.62 9.01-14.14 5.08-19.22 6.97c-6.62 2.46-14.92 9.71-19.64 2.46c-5.32-8.19 5.24-22.07 14.72-24.56z" fill="#f8f9fa"></path><ellipse transform="rotate(-30 12.909 40.928)" cx="12.91" cy="40.93" rx="7.71" ry="9.95" fill="#f8f9fa"></ellipse><ellipse transform="rotate(-30 79.075 82.363)" cx="79.08" cy="82.36" rx="8.01" ry="10.19" fill="#f8f9fa"></ellipse><ellipse transform="rotate(-35.353 67.223 97.302)" cx="67.22" cy="97.3" rx="7.46" ry="10.19" fill="#f8f9fa"></ellipse><ellipse transform="rotate(-3.533 115.05 78.335)" cx="115.06" cy="78.32" rx="7.43" ry="9.46" fill="#f8f9fa"></ellipse></svg>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/sssceta1zw1vjaa1fry32btutp23y920c55wx1bap4af72ld/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/2.0.1/js/dataTables.min.js" defer asp-append-version="true"></script>
    <script src="~/js/site.js" defer asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PetAdoptionMVC/Views/Shared/_Notification.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

@if (TempData["success"] != null)
{
    //This is how you add toastr notifications, need jquery, 
    //the cdn's and to include a script of type  text/js to wrap around toast
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
    
}

@if (TempData["error"] != null)
{
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}