PetAdoptionMVC/Areas/Admin/Controllers/AnimalController.cs
using Microsoft.AspNetCore.Mvc;
using PetAdoption.Models;
using PetAdoption.DataAccess.Data;
using PetAdoption.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using PetAdoption.Utility;

namespace PetAdoptionMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class AnimalController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        
        private readonly IWebHostEnvironment _webHostEnvironment;

        public AnimalController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;

            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            List<Animal> objAnimalList = _unitOfWork.animal.GetAll().ToList();

            return View(objAnimalList);
        }

        public IActionResult Upsert(int? id)
        {
            if (id == null || id == 0)
            {
                return View();
            }
            else
            {
                Animal objAnimal = _unitOfWork.animal.Get(u => u.Id == id);

                return View(objAnimal);
            }
        }

        [HttpPost]
        public IActionResult Upsert(Animal animal, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;

                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);

                    string animalPath = Path.Combine(wwwRootPath, @"Images\Animals");

                    if (!string.IsNullOrEmpty(animal.PhotoUrl))
                    {
                        var oldPhotoPath = Path.Combine(wwwRootPath, animal.PhotoUrl.TrimStart('\\'));

                        if (System.IO.File.Exists(oldPhotoPath))
                        {
                            System.IO.File.Delete(oldPhotoPath);
                        }
                    }

                    using (var fileStream = new FileStream(
                        Path.Combine(animalPath, fileName),
                        FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }

                    animal.PhotoUrl = @"/Images/Animals/" + fileName;
                }
                if (animal.Id == 0)
                {
                    _unitOfWork.animal.Add(animal);

                    _unitOfWork.Save();

                    TempData["success"] = "Animal added successfully";
                }
                else
                {
                    _unitOfWork.animal.Update(animal);

                    _unitOfWork.Save();

                    TempData["success"] = "Animal updated successfully";
                }

                return RedirectToAction("Index");
            }

            var errors = ModelState.Values.SelectMany(x => x.Errors);

            foreach (var error in errors)
            {
                TempData["error"] = error.ErrorMessage;
                break;
            }

            return View();

        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            List<Animal> objAnimalList = _unitOfWork.animal.GetAll().ToList();
            return Json(new { data = objAnimalList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            Animal? animalToBeDeleted = _unitOfWork.animal.Get(u => u.Id == id);
            Listing? listingFromDb = _unitOfWork.listing.Get(u => u.AnimalId == id);

            if (animalToBeDeleted is null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            if (animalToBeDeleted.PhotoUrl is not null)
            {
                var oldPhotoPath = Path.Combine(_webHostEnvironment.WebRootPath, animalToBeDeleted.PhotoUrl.TrimStart('/'));

                if (System.IO.File.Exists(oldPhotoPath))
                {
                    System.IO.File.Delete(oldPhotoPath);
                }
            }

            _unitOfWork.animal.Remove(animalToBeDeleted);

            if (listingFromDb is not null)
            {
                _unitOfWork.listing.Remove(listingFromDb);
            };

            _unitOfWork.Save();

            return Json(new { success = true, message = "Animal removed successfully" });
        }

        #endregion

    }
}

PetAdoptionMVC/Controllers/AnimalController.cs
using Microsoft.AspNetCore.Mvc;
using PetAdoption.Models;
using PetAdoption.DataAccess.Data;
using PetAdoption.DataAccess.Repository.IRepository;

namespace PetAdoptionMVC.Controllers
{
    public class AnimalController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public AnimalController(IUnitOfWork unitOfWork) 
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<Animal> objAnimalList = _unitOfWork.animal.GetAll().ToList();
            return View(objAnimalList);
        }
        public IActionResult Create() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Animal animal) 
        {
            if(ModelState.IsValid) 
            {
                _unitOfWork.animal.Add(animal);
                _unitOfWork.Save();
                TempData["success"] = "Animal added successfully";

                return RedirectToAction("Index");
            }
            TempData["error"] = "Error adding animal";
            return View();
   
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0) 
            {
                return NotFound();
            }
            Animal? animalFromDb = _unitOfWork.animal.Get(u=>u.Id==id);

            if (animalFromDb == null) 
            {
                return NotFound();
            }

            return View(animalFromDb);
        }

        [HttpPost]
        public IActionResult Edit(Animal animal) 
        {
            if (ModelState.IsValid) 
            {
                _unitOfWork.animal.Update(animal);
                _unitOfWork.Save();
                TempData["success"] = "Animal updated successfully";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Error adding animal";
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0) 
            {
                return NotFound();
            }

            Animal? animalFromDb = _unitOfWork.animal.Get(u => u.Id == id);

            if (animalFromDb == null) 
            {
                return NotFound();
            }

            return View(animalFromDb);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult Delete(int id) 
        {
            Animal? animalFromDb = _unitOfWork.animal.Get(u => u.Id == id);

            if(animalFromDb == null) 
            {
                return NotFound();
            }

            _unitOfWork.animal.Remove(animalFromDb);
            _unitOfWork.Save();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");
        }

    }
}

PetAdoptionMVC/Areas/Admin/Views/Animal/Edit.cshtml
@model Animal

<div class="card shadow border-0 pb-3 card-margin">

    <div class="card-header bg-primary bg-gradient ml-0 py-3">

        <div class="row">

            <div class="col-12 text-center">

                <h2 class="text-white">Edit details of the animal</h2>

            </div>

        </div>

    </div>

    <div class="card-body">

        <form method="post" class="row">

            <div class="border-0 px-4">

                <div class="form-floating py-2 col-12">

                    <input asp-for="Name" class="form-control shadow" />

                    <label asp-for="Name" class="ms-2"></label>


                </div>

                <div class="form-floating py-2 col-12">

                    <input asp-for="Age" class="form-control shadow" />

                    <label asp-for="Age" class="ms-2"></label>

                    <span asp-validation-for="Age" class="text-danger"></span>

                </div>

                <div class="form-floating py-2 col-12">

                    <select asp-for="Species" class="form-control shadow">
                        <option value="Cat">Cat</option>
                        <option value="Dog">Dog</option>
                    </select>

                    <label asp-for="Species" class="ms-2"></label>

                </div>

                <div class="form-floating py-2 col-12">

                    <input asp-for="Breed" class="form-control shadow" />

                    <label asp-for="Breed" class="ms-2"></label>

                </div>

                <div class="form-floating py-2 col-12">

                    <select asp-for="Sex" class="form-control shadow">
                        <option value=""></option>
                        <option value="Male">Male</option>
                        <option value="Female">Female</option>
                    </select>

                    <label asp-for="Sex" class="ms-2"></label>

                </div>

                <div class="form-floating py-2 col-12">

                    <select asp-for="Size" class="form-control shadow">
                        <option value="Small">Small</option>
                        <option value="Medium">Medium</option>
                        <option value="Large">Large</option>
                    </select>

                    <label asp-for="Size" class="ms-2"></label>

                </div>

                <div class="form-floating py-2 col-12">

                    <input asp-for="Description" class="form-control shadow" />

                    <label asp-for="Description" class="ms-2"></label>

                </div>

                <div class="form-floating py-2 col-12">

                    <input asp-for="PhotoUrl" class="form-control shadow" />

                    <label asp-for="PhotoUrl" class="ms-2"></label>

                </div>

                <div class="row pt-3">

                    <div class="col-6">
                        <button type="submit" class="btn btn-primary rounded-left form-control">Finish Editing</button>
                    </div>

                    <div class="col-6">

                        <a asp-controller="Animal"
                           asp-action="Index"
                           class="btn btn-warning form-control rounded-right">
                            Back to List
                        </a>

                    </div>

                </div>

            </div>

        </form>

    </div>

</div>

PetAdoptionMVC/Areas/Admin/Views/Animal/Index.cshtml
@model List<Animal>

<div class="card shadow border-0 pb-3 card-margin">

    <div class="card-header bg-primary bg-gradient ml-0 py-3">

        <div class="row">

            <div class="col-8">

                <h2 class="text-white mx-3 px-4 crisp-text">Animals Looking for a Forever Home</h2>

            </div>

            <div class="col-4 text-end px-4">

                <a asp-controller="Animal"
                   asp-action="Upsert"
                   class="btn border btn-outline-secondary text-white crisp-text">
                    <i class="bi bi-plus-circle crisp-text"> Add Animal</i>
                </a>

            </div>

        </div>

    </div>

    <div class="card-body">

        <table id="tblData" class="table table-bordered border-easy" style="width: 100%">

            <thead>

                <tr>

                    <th class="col-3">
                        Name
                    </th>

                    <th class="col-1">
                        Age
                    </th>

                    <th class="col-1">
                        Species
                    </th>

                    <th class="col-2">
                        Breed
                    </th>

                    <th class="col-1">
                        Sex
                    </th>

                    <th class="col-3">
                        Photo
                    </th>

                    <th>
                        <i class="bi bi-pencil-square"></i> / <i class="bi bi-trash"></i>
                    </th>

                </tr>

            </thead>

        </table>

    </div>

</div>

@section Scripts
{
    <script src="~/js/animal.js"></script>
}

PetAdoptionMVC/Areas/Admin/Views/Animal/Upsert.cshtml
@model Animal

<div class="card shadow border-0 pb-3 card-margin">

    <div class="card-header bg-primary bg-gradient ml-0 py-3">

        <div class="row">

            <div class="col-12 text-center">

                <h2 class="text-white crisp-text">@(!Animal.modelProvided(Model) ? "Enter details for new animal" : "Update details of the animal")</h2>

            </div>

        </div>

    </div>

    <div class="card-body">

        <form method="post" class="row" enctype="multipart/form-data">

            <input asp-for="PhotoUrl" hidden />

            <div class="row">

                <div class="col-10">

                    <div class="border-0 px-4">

                        <div class="form-floating py-2 col-12">

                            <input asp-for="Name" class="form-control shadow" />

                            <label asp-for="Name" class="ms-2"></label>


                        </div>

                        <div class="form-floating py-2 col-12">

                            <input asp-for="Age" class="form-control shadow" />

                            <label asp-for="Age" class="ms-2"></label>

                            <span asp-validation-for="Age" class="text-danger"></span>

                        </div>

                        <div class="form-floating py-2 col-12">

                            <select asp-for="Species" class="form-control shadow">
                                <option disabled>---Select Species---</option>
                                <option value="Cat">Cat</option>
                                <option value="Dog">Dog</option>
                            </select>

                            <label asp-for="Species" class="ms-2"></label>

                        </div>

                        <div class="form-floating py-2 col-12">

                            <input asp-for="Breed" class="form-control shadow" />

                            <label asp-for="Breed" class="ms-2"></label>

                        </div>

                        <div class="form-floating py-2 col-12">

                            <select asp-for="Sex" class="form-control shadow">
                                <option disabled>---Select a Sex---</option>
                                <option value=""></option>
                                <option value="Male">Male</option>
                                <option value="Female">Female</option>
                            </select>

                            <label asp-for="Sex" class="ms-2"></label>

                        </div>

                        <div class="form-floating py-2 col-12">

                            <select asp-for="Size" class="form-control shadow">
                                <option disabled>---Select a Size---</option>
                                <option value="Small">Small</option>
                                <option value="Medium">Medium</option>
                                <option value="Large">Large</option>
                            </select>

                            <label asp-for="Size" class="ms-2"></label>

                        </div>

                        <div class="form-floating py-2 col-12">

                            <input type="file" name="file" class="form-control shadow" />

                            <label asp-for="PhotoUrl" class="ms-2"></label>

                        </div>

                        <div class="py-2 col-12 shadow">

                            <label asp-for="Description" class="tinymce-label text-muted"></label>

                            <textarea asp-for="Description" class="form-control shadow"></textarea>

                        </div>

                        <div class="row pt-3">

                            <div class="col-6">

                                @if (!Animal.modelProvided(Model))
                                {
                                    <button type="submit" class="btn btn-primary rounded-left form-control crisp-text">Add Animal</button>
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-primary rounded-left form-control crisp-text">Finish editing</button>
                                }

                            </div>

                            <div class="col-6">

                                <a asp-controller="Animal"
                                   asp-action="Index"
                                   class="btn btn-warning form-control rounded-right crisp-text">
                                    Back to List
                                </a>

                            </div>

                        </div>

                    </div>

                </div>

                <div class="col-2">

                    @if (Animal.modelProvided(Model))
                    {
                        <img src="@Model.PhotoUrl" class="animal-listing-img"/>
                    }

                </div>

            </div>   

        </form>

    </div>

</div>

@section Scripts
{
    <script>
        tinymce.init({
            selector: 'textarea',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
            tinycomments_mode: 'embedded',
            tinycomments_author: 'Author name',
            mergetags_list: [
                { value: 'First.Name', title: 'First Name' },
                { value: 'Email', title: 'Email' },
            ],
            ai_request: (request, respondWith) => respondWith.string(() => Promise.reject("See docs to implement AI Assistant")),
        });
    </script>
}